version: '3.8'

services: 
    dbgo:
        image: mysql
        container_name: 'dbgo'
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go_db
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:  
             - 8083:3306
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
    