version: '3.8'

services: 
    dbgo:
        image: mysql
        container_name: mysql-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go_db
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:  
             - 33060:33060
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        extra_hosts:
            - "host.docker.internal:host-gateway"
    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080
           